### ISSUE TITLE
cs slide fixes

### ISSUE THREAD

**Issue by jovo** [neurodata/ndintro#10]
- [ ] update image benchmarks with new data @MrAE 
- [ ] add ramon benchmarks
- [ ] add grutedb benchmarks
- [ ] replace tile read speed with ggplot @MrAE 
- [ ] ndlims slide @j6k4m8 (or @willgray )
- [ ] ndviz example images @alexbaden 
- [ ] gx example images 
- [ ] mx example images (ivan put image in quarterly report)
- [ ] ndparse slides @willgray 
- [ ] f2g slide @ebridge2 
- [ ] image analysis @alexbaden 
- [ ] ref2 @MrAE

**Comment by MrAE** [comment]
- [x] Micholas Charon --> Nicholas Charon

**Comment by MrAE** [comment]
- [x] fix "Utilies" --> "Utilities"

**Comment by MrAE** [comment]
- [ ] update image benchmarks = replace with new ones from cvs files & add tile_cache_benchmark and add S.E.M.
